name = "cf-pathproxy"
main = "_worker.js"
compatibility_date = "2024-03-01"

# 使用环境变量动态绑定 KV（避免硬编码 ID）
kv_namespaces = [
  { binding = "CONFIG_KV", id = "${CONFIG_KV_ID}" },
  { binding = "AUTH_KV", id = "${AUTH_KV_ID}" }
]

[build]
upload.format = "modules"
